enum ContentType {
  COMMERCIAL,
  FOOD,
  RESTAURANT,
  SHOPPING,
  SIGHT,
  NIGHT_LIFE,
  ACCOMMODATION,
  EDUCATION,
  CHILDCARE,
  ENTERTAINMENT,
  HEALTHCARE,
  LEISURE,
  NATURAL,
  PARKING,
  RENTAL,
  SERVICE,
  TOURISM,
  ADULT,
  BUILDING,
  PUBLIC_TRANSPORT,
  ADMINISTRATIVE,
}

enum FreeEventCategory {SIGHTS, NIGHTLIFE, RESTAURANT, SHOPPING}


const Map<ContentType, String> categories = {
  ContentType.COMMERCIAL: "commercial",
  ContentType.FOOD: "food",
  ContentType.ACCOMMODATION: "accommodation",
  ContentType.EDUCATION: "education",
  ContentType.CHILDCARE: "childcare",
  ContentType.ENTERTAINMENT: "entertainment",
  ContentType.HEALTHCARE: "healthcare",
  ContentType.LEISURE: "leisure",
  ContentType.NATURAL: "natural",
  ContentType.PARKING: "parking",
  ContentType.RENTAL: "commercial",
  ContentType.SERVICE: "service",
  ContentType.TOURISM: "tourism",
  ContentType.ADULT: "adult",
  ContentType.BUILDING: "building",
  ContentType.PUBLIC_TRANSPORT: "public transport",
  ContentType.ADMINISTRATIVE: "administrative",
};